on:
  push:
    branches:
      - main
name: CI Staging
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: staging
      cancel-in-progress: true
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Get nova setup for installation
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Install front-end dependencies
        run: |
          npm install
          npm run build

      - name: Prepare Venture
        run: |
          cp .env.ci .env.testing

      - name: Run Testsuite
        run: vendor/bin/pest

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: staging
      cancel-in-progress: true

    steps:
      - name: Deploy to Laravel Forge
        run: curl ${{ secrets.FORGE_PRODUCTION_DEPLOYMENT_WEBHOOK }}
