on: push
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-sqlite@v1
        with:
          sqlite-version: 3.40.0
          sqlite-year: 2022

      - name: Get nova setup for installation
        run: |
          composer config "http-basic.nova.laravel.com" "justin.t.werner@gmail.com" "G4JBFED9GlVIoHiAd4KpEouhZR32oOANpoKkqEaNZP3ThkZ5BL"

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Install front-end dependencies
        run: |
          npm install
          npm run build

      - name: Prepare Venture
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/pest

#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Deploy to Laravel Forge
#        run: curl ${{ secrets.FORGE_DEPLOYMENT_WEBHOOK }}
